apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
patchesJson6902:
- path: patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: "${SERVICE_NAME}"
